Repository getsentry/sentry-ruby, pull requests merged in 2020-08, with the labels that each got.

#972 Add tests for release detection
  Gemfile
  spec/raven/configuration_spec.rb
  spec/spec_helper.rb
Labels: testing

#973 Remove RUBY_VERSION checks that are under Ruby 2.3
  Gemfile
  spec/raven/integrations/sidekiq_spec.rb
  spec/raven/json_spec.rb
Labels: refactoring

#977 Fix frozen string issues
  .travis.yml
  lib/raven/configuration.rb
  spec/raven/event_spec.rb
  spec/raven/processors/utf8conversion_spec.rb
Labels: bug fix

#980 Use version-insensitive Sidekiq interface in tests
  .travis.yml
  Gemfile
  spec/raven/integrations/sidekiq_spec.rb
Labels: testing

#981 Speed up jruby CI test suite
  .travis.yml
  Gemfile
  cleanup_bundler
Labels: testing

#982 Support Rails 6
  .travis.yml
  Gemfile
  lib/raven/integrations/rails.rb
  spec/support/test_rails_app/app.rb
Labels: enhancement

#974 Rubocop upgrade and style fixes
  .rubocop.yml
  Gemfile
  lib/raven/backtrace.rb
  lib/raven/base.rb
  lib/raven/breadcrumbs.rb
  lib/raven/breadcrumbs/activesupport.rb
  lib/raven/breadcrumbs/logger.rb
  lib/raven/cli.rb
  lib/raven/client.rb
  lib/raven/configuration.rb
  lib/raven/event.rb
  lib/raven/instance.rb
  lib/raven/integrations/delayed_job.rb
  lib/raven/integrations/rack-timeout.rb
  lib/raven/integrations/rack.rb
  lib/raven/integrations/rails/active_job.rb
  lib/raven/integrations/rails/overrides/debug_exceptions_catcher.rb
  lib/raven/interface.rb
  lib/raven/interfaces/stack_trace.rb
  lib/raven/linecache.rb
  lib/raven/logger.rb
  lib/raven/processor/cookies.rb
  lib/raven/processor/post_data.rb
  lib/raven/processor/removecircularreferences.rb
  lib/raven/processor/sanitizedata.rb
  lib/raven/processor/utf8conversion.rb
  lib/raven/transports/http.rb
  lib/raven/utils/exception_cause_chain.rb
  lib/raven/utils/real_ip.rb
  lib/raven/version.rb
  spec/raven/integrations/rails/activejob_spec.rb
  spec/raven/integrations/sidekiq_spec.rb
  spec/raven/processors/cookies_spec.rb
  spec/raven/processors/post_data_spec.rb
  spec/raven/processors/removecirculareferences_spec.rb
  spec/raven/processors/utf8conversion_spec.rb
  spec/spec_helper.rb
Labels: refactoring

#983 Masking cookies as key/pair instead of a single string
  lib/raven/processor/cookies.rb
  spec/raven/processors/cookies_spec.rb
Labels: bug fix

#986 Fix transports classes' requiring issue
  lib/raven/client.rb
  lib/raven/transports.rb
  spec/raven/client_spec.rb
  spec/spec_helper.rb
Labels: bug fix

#984 Improve SanitizeData processor
  lib/raven/processor/sanitizedata.rb
  spec/raven/processors/sanitizedata_processor_spec.rb
Labels: bug fix

#987 Replace travis-ci with GH actions
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: testing, wip

#988 Minor improvements
  .github/workflows/test.yml
  README.md
  cleanup_bundler
Labels: documentation, refactoring, testing

#989 Fix/Refactor Raven::Cli
  lib/raven/cli.rb
  spec/raven/cli_spec.rb
Labels: bug fix, refactoring, testing

#993 Fix broken links in doc
  CHANGELOG.md
  README.md
Labels: documentation

#958 Improve DSN section in README
  README.md
Labels: documentation

#1000 Don't log warning messages when it doesn't need to
  lib/raven/configuration.rb
  lib/raven/instance.rb
  spec/raven/instance_spec.rb
Labels: bug fix

#1002 Revert "Refactor Client class #995"
  lib/raven/client.rb
  lib/raven/event.rb
  spec/raven/client_spec.rb
  spec/raven/event_spec.rb
  spec/raven/integration_spec.rb
Labels: bug fix

#1005 Accept non-string message in Event.from_exception
  lib/raven/event.rb
  spec/raven/event_spec.rb
Labels: bug fix

#1008 docs: Fix CONTRIBUTING.md typo
  CONTRIBUTING.md
Labels: documentation

#1007 Fix merge error from rack-timeout raven_context on old releases
  lib/raven/integrations/rack-timeout.rb
  spec/raven/integrations/rack_timeout_spec.rb
Labels: bug fix
