Repository getsentry/sentry-ruby, pull requests merged in 2020-09, with the labels that each got.

#1006 Deprecate dasherized filenames
  lib/raven/helpers/deprecation_helper.rb
  lib/raven/integrations/rack-timeout.rb
  lib/raven/integrations/rack_timeout.rb
  lib/sentry-raven-without-integrations.rb
  lib/sentry_raven_without_integrations.rb
  spec/raven/integration_spec.rb
  spec/raven/integrations/rack_timeout_spec.rb
  spec/spec_helper.rb
Labels: refactoring

#1010 Refactor event initialization
  lib/raven/event.rb
  lib/raven/instance.rb
  spec/raven/client_spec.rb
  spec/raven/event_spec.rb
  spec/raven/instance_spec.rb
  spec/raven/processors/removestacktrace_spec.rb
  spec/raven/transports/http_spec.rb
  spec/raven/transports/stdout_spec.rb
Labels: refactoring

#1011 Support cleaning up exception backtrace with customized backtrace_cleaner
  .rubocop.yml
  lib/raven/backtrace.rb
  lib/raven/configuration.rb
  lib/raven/event.rb
  lib/raven/integrations/rails.rb
  lib/raven/integrations/rails/backtrace_cleaner.rb
  spec/raven/backtrace_spec.rb
  spec/raven/configuration_spec.rb
  spec/raven/integrations/rails_spec.rb
  spec/support/test_rails_app/app.rb
Labels: enhancement

#1012 Make dsn value accessable from config
  lib/raven/configuration.rb
  spec/raven/configuration_spec.rb
Labels: enhancement

#1013 Add tests on our breadcrumbs integrations
  .gitignore
  benchmarks/allocation_comparison.rb
  benchmarks/allocation_report.rb
  benchmarks/async_benchmark.rb
  benchmarks/benchmark.rb
  benchmarks/benchmark.yml
  benchmarks/profile.rb
  examples/rails-6.0/config/application.rb
  lib/raven/breadcrumbs/activesupport.rb
  spec/raven/breadcrumbs/active_support_breadcrumbs_spec.rb
  spec/raven/breadcrumbs/breadcrumb_logger_spec.rb
  spec/raven/integrations/rails_spec.rb
  spec/support/test_rails_app/app.rb
Labels: testing

#1014 Remove BreadcrumbLogger's unused error handling
  lib/raven/breadcrumbs/logger.rb
  spec/raven/breadcrumbs/breadcrumb_logger_spec.rb
Labels: refactoring

#1015 Unify breadcrumbs logger naming
  lib/raven/breadcrumbs/active_support_logger.rb
  lib/raven/breadcrumbs/activesupport.rb
  lib/raven/breadcrumbs/logger.rb
  lib/raven/breadcrumbs/sentry_logger.rb
  lib/raven/integrations/rails.rb
  spec/raven/breadcrumbs/active_support_breadcrumbs_spec.rb
  spec/raven/breadcrumbs/sentry_logger_spec.rb
Labels: refactoring

#1016 Unify breadcrumb loggers activation
  .rubocop.yml
  examples/rails-6.0/config/application.rb
  lib/raven/base.rb
  lib/raven/breadcrumbs/logger.rb
  lib/raven/cli.rb
  lib/raven/configuration.rb
  lib/raven/helpers/deprecation_helper.rb
  lib/raven/integrations/rails.rb
  spec/raven/breadcrumbs/active_support_breadcrumbs_spec.rb
  spec/raven/breadcrumbs/sentry_logger_spec.rb
  spec/raven/configuration_spec.rb
Labels: enhancement, refactoring

#1017 Replace sys_command usages in context.rb
  lib/raven/context.rb
Labels: enhancement

#1018 Setup sidekiq in the example app
  examples/rails-6.0/Gemfile
  examples/rails-6.0/README.md
  examples/rails-6.0/app/workers/error_worker.rb
  examples/rails-6.0/config/routes.rb
Labels: testing

#1019 Refactor sidekiq integration
  lib/raven/integrations/sidekiq.rb
  lib/raven/integrations/sidekiq/cleanup_middleware.rb
  lib/raven/integrations/sidekiq/context_filter.rb
  lib/raven/integrations/sidekiq/error_handler.rb
  spec/raven/integrations/sidekiq/error_handler_spec.rb
  spec/raven/integrations/sidekiq_spec.rb
Labels: refactoring, sidekiq

#1020 Sidekiq integration test
  .github/workflows/test.yml
  spec/raven/integrations/sidekiq_spec.rb
Labels: testing

#1026 Revert rack-timeout deprecation
  examples/rails-6.0/Gemfile
  lib/raven/integrations/rack-timeout.rb
  lib/raven/integrations/rack_timeout.rb
  spec/raven/integrations/rack_timeout_spec.rb
Labels: bug fix

#1028 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#860 Enable configurable rack environment recorded parameters. Fix #854.
  lib/raven/configuration.rb
  lib/raven/integrations/rack.rb
  spec/raven/integrations/rack_spec.rb
Labels: enhancement

#1023 Allow blocks on user_context
  lib/raven/instance.rb
  spec/raven/instance_spec.rb
Labels: enhancement

#1031 Transplant classes
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/interface.rb
  sentry-ruby/lib/sentry/interfaces/exception.rb
  sentry-ruby/lib/sentry/interfaces/http.rb
  sentry-ruby/lib/sentry/interfaces/message.rb
  sentry-ruby/lib/sentry/interfaces/single_exception.rb
  sentry-ruby/lib/sentry/interfaces/stack_trace.rb
  sentry-ruby/lib/sentry/logger.rb
  sentry-ruby/lib/sentry/transports.rb
  sentry-ruby/lib/sentry/transports/dummy.rb
  sentry-ruby/lib/sentry/transports/http.rb
  sentry-ruby/lib/sentry/transports/stdout.rb
  sentry-ruby/lib/sentry/utils/deep_merge.rb
  sentry-ruby/lib/sentry/utils/exception_cause_chain.rb
  sentry-ruby/sentry-ruby.gemspec
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/interface_spec.rb
  sentry-ruby/spec/sentry/interfaces/stack_trace_spec.rb
  sentry-ruby/spec/sentry/transports/http_spec.rb
  sentry-ruby/spec/sentry/transports/stdout_spec.rb
  sentry-ruby/spec/spec_helper.rb
Labels: enhancement

#1032 Build simple client
  sentry-ruby/Gemfile
  sentry-ruby/lib/sentry/backtrace.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/client/state.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/interfaces/stack_trace.rb
  sentry-ruby/lib/sentry/linecache.rb
  sentry-ruby/lib/sentry/utils/deep_merge.rb
  sentry-ruby/spec/sentry/backtrace_spec.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/interfaces/stack_trace_spec.rb
  sentry-ruby/spec/sentry/linecache_spec.rb
  sentry-ruby/spec/spec_helper.rb
  sentry-ruby/spec/support/linecache.txt
Labels: enhancement

#1033 Add request id to headers if exists
  lib/raven/integrations/rack.rb
  spec/raven/integrations/rack_spec.rb
Labels: enhancement

#898 Remove ActiveJob keys for both Sidekiq and DelayedJob
  lib/raven/integrations/delayed_job.rb
  lib/raven/integrations/sidekiq/error_handler.rb
  lib/raven/utils/context_filter.rb
  spec/raven/integrations/sidekiq/error_handler_spec.rb
  spec/raven/utils/context_filter_spec.rb
Labels: enhancement

#1035 Remove circular dependency in transport/http.rb
  lib/raven/transports/http.rb
Labels: refactoring

#1038 Add Scope class
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/breadcrumb.rb
  sentry-ruby/lib/sentry/breadcrumb_buffer.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/sentry/transports/http_spec.rb
Labels: enhancement

#1039 Fix spec
  .github/workflows/sentry_raven_test.yml
  .github/workflows/sentry_ruby_test.yml
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/sentry/transports/stdout_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: testing
