Repository getsentry/sentry-ruby, pull requests merged in 2020-10, with the labels that each got.

#1043 Refactoring from #1040
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/event/options.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
Labels: refactoring

#1044 Add Hub class
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/breadcrumb_buffer.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/core_ext/object/deep_dup.rb
  sentry-ruby/lib/sentry/core_ext/object/duplicable.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1045 Add top-level static APIs
  sentry-ruby/lib/sentry.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: enhancement

#1046 Support breadcrumb helpers
  sentry-ruby/lib/sentry/breadcrumb_buffer.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1047 Support contexts
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/event/options.rb
  sentry-ruby/lib/sentry/ruby.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/sentry-ruby.gemspec
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1048 Add Scope setters
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/scope/setters_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1042 fix: correct extra_context method name and ussage for README
  README.md
Labels: documentation

#1052 Add Layer class to contain both client and scope in the same stack
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: enhancement

#1053 Move Event sending logic into Transport class
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/transports.rb
  sentry-ruby/lib/sentry/transports/dummy.rb
  sentry-ruby/lib/sentry/transports/http.rb
  sentry-ruby/lib/sentry/transports/state.rb
  sentry-ruby/lib/sentry/transports/stdout.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
  sentry-ruby/spec/sentry/transports/http_spec.rb
  sentry-ruby/spec/sentry/transports/stdout_spec.rb
Labels: refactoring

#1054 Extract dsn processing out of Configuration class
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/dsn.rb
  sentry-ruby/lib/sentry/transports.rb
  sentry-ruby/lib/sentry/transports/http.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/dsn_spec.rb
Labels: refactoring

#1055 Add better support for Hub switching
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: enhancement

#1056 Rename Transport classes
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/dummy_transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/lib/sentry/transport/state.rb
  sentry-ruby/lib/sentry/transport/stdout_transport.rb
  sentry-ruby/lib/sentry/transports.rb
  sentry-ruby/lib/sentry/transports/dummy.rb
  sentry-ruby/lib/sentry/transports/http.rb
  sentry-ruby/lib/sentry/transports/stdout.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/transport/http_transport_spec.rb
  sentry-ruby/spec/sentry/transport/stdout_transport_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: refactoring

#1057 Fix Delayed::Plugins::Raven when job raises exception
  Gemfile
  lib/raven/integrations/delayed_job.rb
  spec/raven/integrations/delayed_job_spec.rb
Labels: bug fix

#1059 Transport options
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/configuration.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/transport/configuration_spec.rb
  sentry-ruby/spec/sentry/transport/http_transport_spec.rb
Labels: enhancement, refactoring

#1060 Drop #scheme config option
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/stdout_transport.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/sentry/transport/stdout_transport_spec.rb
  sentry-ruby/spec/sentry_spec.rb
  sentry-ruby/spec/spec_helper.rb
Labels: refactoring

#1050 Rack integration
  sentry-ruby/Gemfile
  sentry-ruby/examples/rails-6.0/Gemfile
  sentry-ruby/examples/rails-6.0/app/controllers/welcome_controller.rb
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/examples/rails-6.0/config/unicorn.rb
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/event/options.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/capture_exception.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/lib/sentry/utils/real_ip.rb
  sentry-ruby/spec/sentry/rack/capture_exception_spec.rb
  sentry-ruby/spec/sentry/rack/rack_interface_spec.rb
  sentry-ruby/spec/sentry/scope/setters_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1064 Merge hash instead of replacing the original value in user_context
  lib/raven/instance.rb
  spec/raven/instance_spec.rb
Labels: bug fix

#1065 Breadcrumb support
  sentry-ruby/examples/rails-6.0/Gemfile
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/examples/rails-6.0/config/unicorn.rb
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/breadcrumb/sentry_logger.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/rack/capture_exception.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/breadcrumb/sentry_logger_spec.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/rack/capture_exception_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: enhancement

#1067 Support specifying custom transport class
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/transport/configuration.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/transport/configuration_spec.rb
Labels: enhancement

#1069 Update workflow configs
  .github/workflows/sentry_rails_test.yml
  .github/workflows/sentry_raven_test.yml
  .github/workflows/sentry_ruby_test.yml
  sentry-rails/Gemfile
Labels: testing

#1070 Migrate Rails-only config options
  sentry-rails/lib/sentry/rails.rb
  sentry-rails/lib/sentry/rails/configuration.rb
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/spec/sentry/rails/configuration_spec.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-rails/spec/spec_helper.rb
  sentry-rails/spec/support/test_rails_app/app.rb
  sentry-ruby/lib/sentry/configuration.rb
Labels: refactoring

#1074 Allow SDK extensions to specify custom metadata
  sentry-rails/lib/sentry/rails.rb
  sentry-rails/spec/sentry/rails/event_spec.rb
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/event.rb
Labels: refactoring

#1075 sentry-sidekiq
  .github/workflows/sentry_raven_test.yml
  .github/workflows/sentry_sidekiq_test.yml
  sentry-sidekiq/.gitignore
  sentry-sidekiq/.rspec
  sentry-sidekiq/.travis.yml
  sentry-sidekiq/CODE_OF_CONDUCT.md
  sentry-sidekiq/Gemfile
  sentry-sidekiq/LICENSE.txt
  sentry-sidekiq/README.md
  sentry-sidekiq/Rakefile
  sentry-sidekiq/bin/console
  sentry-sidekiq/bin/setup
  sentry-sidekiq/example/Gemfile
  sentry-sidekiq/example/README.md
  sentry-sidekiq/example/config/sidekiq.yml
  sentry-sidekiq/example/error_worker.rb
  sentry-sidekiq/lib/sentry/sidekiq.rb
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/context_filter.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
  sentry-sidekiq/lib/sentry/sidekiq/version.rb
  sentry-sidekiq/sentry-sidekiq.gemspec
  sentry-sidekiq/spec/sentry/sidekiq/context_filter_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq/error_handler_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
  sentry-sidekiq/spec/spec_helper.rb
Labels: enhancement, sidekiq

#1077 Add codecov to new gems
  .github/workflows/sentry_sidekiq_test.yml
  sentry-rails/Gemfile
  sentry-rails/spec/spec_helper.rb
  sentry-ruby/Gemfile
  sentry-ruby/spec/spec_helper.rb
  sentry-sidekiq/Gemfile
  sentry-sidekiq/spec/spec_helper.rb
Labels: testing

#1078 Add send_default_pii config option
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/rack/rack_interface_spec.rb
Labels: enhancement

#1079 Support sending events in envelope format with HTTPEnvelopeTransport
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/lib/sentry/dsn.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_envelope_transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/dsn_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/transport/http_envelope_transport_spec.rb
Labels: enhancement

#1081 Replace HTTPTransport with HTTPEnvelopeTransport
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/lib/sentry/dsn.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_envelope_transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/dsn_spec.rb
  sentry-ruby/spec/sentry/transport/http_envelope_transport_spec.rb
  sentry-ruby/spec/sentry/transport/http_transport_spec.rb
Labels: enhancement

#1082 Remove unused event attributes
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/event/options.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/capture_exception.rb
  sentry-ruby/spec/sentry/client_spec.rb
Labels: refactoring

#1083 Remove MessageInterface
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/interface.rb
  sentry-ruby/lib/sentry/interfaces/message.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/interface_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
Labels: refactoring

#1085 Refactor Rails patches
  sentry-rails/lib/sentry/rails/controller_methods.rb
  sentry-rails/lib/sentry/rails/overrides/debug_exceptions_catcher.rb
  sentry-rails/spec/sentry/rails/controller_methods_spec.rb
  sentry-rails/spec/sentry/rails/overrides/debug_exceptions_catcher_spec.rb
Labels: refactoring

#1084 Refactorings
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/capture_exception.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/rack/capture_exception_spec.rb
Labels: refactoring, wip

#1087 Don't add message param when capturing exceptions
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
  sentry-sidekiq/spec/sentry/sidekiq/error_handler_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
Labels: sidekiq

#1088 Rename & simplify interfaces
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/interface.rb
  sentry-ruby/lib/sentry/interfaces/exception.rb
  sentry-ruby/lib/sentry/interfaces/request.rb
  sentry-ruby/lib/sentry/interfaces/single_exception.rb
  sentry-ruby/lib/sentry/interfaces/stacktrace.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/spec/sentry/interface_spec.rb
  sentry-ruby/spec/sentry/interfaces/stacktrace_spec.rb
  sentry-ruby/spec/sentry/rack/rack_interface_spec.rb
Labels: refactoring

#1089 Merge Request and Rack interface classes
  sentry-ruby/lib/sentry/interfaces/request.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/spec/sentry/interfaces/request_interface_spec.rb
Labels: refactoring

#1090 Remove ip addresses if send_default_pii is set to false (default)
  sentry-ruby/lib/sentry/interfaces/request.rb
  sentry-ruby/lib/sentry/utils/real_ip.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/interfaces/request_interface_spec.rb
  sentry-ruby/spec/sentry/utils/real_ip_spec.rb
Labels: enhancement
