Repository getsentry/sentry-ruby, pull requests merged in 2020-12, with the labels that each got.

#1122 Support event hint
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
Labels: enhancement

#1119 Add: Request ID to tags for Raven::Event
  lib/raven/base.rb
  lib/raven/event.rb
  lib/raven/integrations/rack.rb
  lib/raven/utils/request_id.rb
  spec/raven/event_spec.rb
  spec/raven/utils/request_id_spec.rb
Labels: enhancement

#1123 Interface improvements
  MIGRATION.md
  sentry-rails/examples/rails-6.0/app/controllers/welcome_controller.rb
  sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/breadcrumb.rb
  sentry-ruby/lib/sentry/breadcrumb/sentry_logger.rb
  sentry-ruby/lib/sentry/breadcrumb_buffer.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/spec/sentry/breadcrumb/sentry_logger_spec.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
Labels: enhancement

#1120 Add Request ID to tags for Sentry::Event
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/interfaces/request.rb
  sentry-ruby/lib/sentry/utils/request_id.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/utils/request_id_spec.rb
Labels: enhancement

#1127 Fix typo in the migrations guide
  MIGRATION.md
Labels: documentation

#1128 Support rails 6.1
  .github/workflows/sentry_rails_test.yml
  .github/workflows/sentry_raven_test.yml
  sentry-rails/Gemfile
  sentry-rails/spec/sentry/rails/active_support_breadcrumbs_spec.rb
Labels: enhancement, rails

#1132 ActiveSupportLogger should only record events that has a started time
  sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
  sentry-rails/spec/sentry/rails/active_support_breadcrumbs_spec.rb
Labels: bug fix, rails

#1135 Make Event's interfaces accessible
  sentry-ruby/lib/sentry/event.rb
Labels: bug fix

#1137 Add rake integration
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/rake.rb
  sentry-ruby/spec/sentry/rake_spec.rb
  sentry-ruby/spec/support/Rakefile.rb
Labels: enhancement

#1143 Fix issue #1110
  sentry-raven/lib/raven/transports/http.rb
  sentry-raven/spec/raven/transports/http_spec.rb
Labels: bug fix

#1144 Fix event sampling
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: bug fix

#1147 Merge 2 Rack middlewares
  sentry-rails/lib/sentry/rails/capture_exceptions.rb
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/spec/sentry/rails/tracing/action_controller_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/action_view_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/active_record_subscriber_spec.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-rails/spec/spec_helper.rb
  sentry-ruby/examples/sinatra/app.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/capture_exception.rb
  sentry-ruby/lib/sentry/rack/capture_exceptions.rb
  sentry-ruby/spec/sentry/rack/capture_exception_spec.rb
  sentry-ruby/spec/sentry/rack/tracing_spec.rb
Labels: refactoring

#1148 Deep-copy spans
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/sentry/span_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
Labels: bug fix

#1149 Move span recorder related code from Span to Transaction
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/lib/sentry/transaction.rb
  sentry-ruby/spec/sentry/span_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
Labels: refactoring

#1139 Fix workflow matrix
  .github/workflows/sentry_ruby_test.yml
Labels: testing

#1138 Separate rack integration
  .github/workflows/sentry_ruby_test.yml
  sentry-ruby/Gemfile
  sentry-ruby/examples/without_integrations/Gemfile
  sentry-ruby/examples/without_integrations/app.rb
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/interfaces/request.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/interface.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/interfaces/request_interface_spec.rb
  sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb
  sentry-ruby/spec/sentry/scope/setters_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/spec_helper.rb
Labels: bug fix

#1150 Tidy up rails integration
  sentry-rails/lib/sentry/rails/railtie.rb
Labels: refactoring

#1151 Check SDK initialization before running integrations
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-ruby/examples/rake/Gemfile
  sentry-ruby/examples/rake/Rakefile.rb
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/rack/capture_exceptions.rb
  sentry-ruby/lib/sentry/rake.rb
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
Labels: bug fix

#1154 Refactor transport
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/lib/sentry/transport/state.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: refactoring

#1156 Disabled SDK shouldn't even call the async block
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/spec/sentry/client_spec.rb
Labels: bug fix

#1155 Implement non-blocking event sending
  README.md
  sentry-rails/spec/sentry/rails/controller_methods_spec.rb
  sentry-rails/spec/sentry/rails/overrides/debug_exceptions_catcher_spec.rb
  sentry-rails/spec/spec_helper.rb
  sentry-rails/spec/support/test_rails_app/app.rb
  sentry-ruby/README.md
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/background_worker.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/sentry-ruby.gemspec
  sentry-ruby/spec/sentry/background_worker_spec.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/rack/capture_exceptions_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
  sentry-ruby/spec/spec_helper.rb
  sentry-ruby/spec/support/Rakefile.rb
  sentry-sidekiq/spec/spec_helper.rb
Labels: enhancement

#1158 Add per event backgrounding option
  README.md
  sentry-ruby/README.md
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/rake.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
  sentry-sidekiq/spec/sentry/sidekiq/error_handler_spec.rb
Labels: bug fix

#1157 Update changelogs for 4.1.0
  sentry-rails/CHANGELOG.md
  sentry-ruby/CHANGELOG.md
  sentry-sidekiq/CHANGELOG.md
Labels: documentation

#1159 Use stricter dependency declaration
  sentry-rails/CHANGELOG.md
  sentry-rails/sentry-rails.gemspec
  sentry-sidekiq/CHANGELOG.md
  sentry-sidekiq/sentry-sidekiq.gemspec
Labels: bug fix

#1161 Fix NoMethodError when sending is not allowed
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
Labels: bug fix

#1160 Add notification for users who still use deprecated middlewares
  sentry-ruby/examples/sinatra/app.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/deprecations.rb
  sentry-ruby/spec/sentry/rack/deprecations_spec.rb
Labels: bug fix

#1162 Improve top-level api safety
  sentry-ruby/CHANGELOG.md
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: bug fix

#1164 Fix typo
  README.md
Labels: documentation

#1165 Specify stable codecov version to avoid CI issues
  sentry-rails/Gemfile
  sentry-raven/Gemfile
  sentry-ruby/Gemfile
  sentry-sidekiq/Gemfile
Labels: testing

#1167 before_send callback shouldn't be applied to transaction events
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/spec/sentry/client_spec.rb
Labels: bug fix

#1170 Transaction improvements
  sentry-rails/lib/sentry/rails/capture_exceptions.rb
  sentry-rails/lib/sentry/rails/controller_transaction.rb
  sentry-rails/spec/sentry/rails/tracing_spec.rb
  sentry-rails/spec/support/test_rails_app/app.rb
  sentry-ruby/lib/sentry/rack/capture_exceptions.rb
  sentry-ruby/lib/sentry/transport.rb
Labels: bug fix, rails

#1168 Use middleware instead of method override to handle rescued exceptions
  sentry-rails/lib/sentry/rails/capture_exceptions.rb
  sentry-rails/lib/sentry/rails/overrides/debug_exceptions_catcher.rb
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/lib/sentry/rails/rescued_exception_interceptor.rb
  sentry-rails/spec/sentry/rails/overrides/debug_exceptions_catcher_spec.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-rails/spec/support/test_rails_app/app.rb
Labels: bug fix

#1172 Support Ruby 3
  .github/workflows/sentry_rails_test.yml
  .github/workflows/sentry_ruby_test.yml
  .github/workflows/sentry_sidekiq_test.yml
  sentry-ruby/lib/sentry/span.rb
Labels: enhancement, testing

#1176 test: add regression test for sidekiq retries
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
Labels: testing

#1175 Fix sidekiq middleware
  sentry-sidekiq/lib/sentry-sidekiq.rb
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
  sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb
  sentry-sidekiq/spec/sentry/sidekiq/error_handler_spec.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
  sentry-sidekiq/spec/spec_helper.rb
Labels: bug fix

#1177 Add Integrable module
  EXTENSION.md
  sentry-rails/lib/sentry/rails.rb
  sentry-rails/lib/sentry/rails/active_job.rb
  sentry-rails/lib/sentry/rails/capture_exceptions.rb
  sentry-rails/lib/sentry/rails/controller_methods.rb
  sentry-rails/lib/sentry/rails/overrides/streaming_reporter.rb
  sentry-rails/spec/sentry/rails/event_spec.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/integrable.rb
  sentry-ruby/lib/sentry/rack/capture_exceptions.rb
  sentry-ruby/spec/sentry/integrable_spec.rb
  sentry-sidekiq/lib/sentry-sidekiq.rb
  sentry-sidekiq/lib/sentry/sidekiq/cleanup_middleware.rb
  sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
Labels: bug fix, enhancement
