Repository getsentry/sentry-ruby, pull requests merged in 2020-11, with the labels that each got.

#1093 Correct Processors configuration and Integration links
  README.md
Labels: documentation

#1091 Fix coverage reporting's path overlapping issue
  codecov.yml
  sentry-rails/spec/spec_helper.rb
  sentry-ruby/spec/spec_helper.rb
  sentry-sidekiq/spec/spec_helper.rb
Labels: testing

#1092 Don't exclude ActionView::MissingTemplate error by default
  lib/raven/configuration.rb
  sentry-rails/lib/sentry/rails/configuration.rb
Labels: bug fix, rails

#1086 Allow passing custom scope to Hub#capture* helpers
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/spec/sentry/hub_spec.rb
Labels: enhancement

#1098 Fix async
  sentry-ruby/examples/rails-6.0/app/jobs/sentry_job.rb
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/lib/sentry.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: bug fix

#1099 Update readme
  sentry-rails/README.md
  sentry-ruby/README.md
  sentry-sidekiq/README.md
Labels: documentation

#1100 Cleanup
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/spec/sentry/backtrace_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: refactoring

#1101 Remove Event options
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/event/options.rb
  sentry-ruby/lib/sentry/utils/deep_merge.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: refactoring

#1102 Add migration guide
  MIGRATION.md
  README.md
Labels: documentation

#1103 Fix sdk require issue
  sentry-rails/lib/sentry-rails.rb
  sentry-rails/lib/sentry/rails.rb
  sentry-rails/spec/spec_helper.rb
  sentry-ruby/README.md
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/ruby.rb
  sentry-ruby/spec/spec_helper.rb
  sentry-sidekiq/example/error_worker.rb
  sentry-sidekiq/lib/sentry-sidekiq.rb
  sentry-sidekiq/spec/sentry/sidekiq_spec.rb
  sentry-sidekiq/spec/spec_helper.rb
Labels: bug fix

#1104 Bug fixes
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/http_transport.rb
  sentry-ruby/spec/sentry/event_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: bug fix

#1105 Fix random failures
  sentry-rails/Rakefile
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-ruby/Rakefile
  sentry-ruby/lib/sentry/transport.rb
  sentry-sidekiq/Rakefile
Labels: bug fix, testing

#1106 Fix typo: much -> must for Raven::Event
  lib/raven/event.rb
  spec/raven/event_spec.rb
Labels: bug fix

#1108 Support transaction (part 1)
  .github/workflows/sentry_rails_test.yml
  sentry-rails/Gemfile
  sentry-rails/examples/rails-6.0/config/application.rb
  sentry-rails/lib/sentry/rails.rb
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/lib/sentry/rails/tracing.rb
  sentry-rails/lib/sentry/rails/tracing/abstract_subscriber.rb
  sentry-rails/lib/sentry/rails/tracing/active_record_subscriber.rb
  sentry-rails/spec/sentry/rails/tracing_spec.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-rails/spec/support/test_rails_app/app.rb
  sentry-ruby/examples/rails-6.0/config/application.rb
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/rack.rb
  sentry-ruby/lib/sentry/rack/tracing.rb
  sentry-ruby/lib/sentry/scope.rb
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/lib/sentry/transaction.rb
  sentry-ruby/lib/sentry/transaction_event.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/spec/sentry/client_spec.rb
  sentry-ruby/spec/sentry/hub_spec.rb
  sentry-ruby/spec/sentry/rack/tracing_spec.rb
  sentry-ruby/spec/sentry/scope/setters_spec.rb
  sentry-ruby/spec/sentry/scope_spec.rb
  sentry-ruby/spec/sentry/span_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
  sentry-ruby/spec/sentry/transport/http_transport_spec.rb
  sentry-ruby/spec/sentry/transport_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: enhancement, tracing

#1109 Improve instrumentation
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/lib/sentry/rails/tracing.rb
  sentry-rails/lib/sentry/rails/tracing/abstract_subscriber.rb
  sentry-rails/lib/sentry/rails/tracing/action_controller_subscriber.rb
  sentry-rails/lib/sentry/rails/tracing/action_view_subscriber.rb
  sentry-rails/lib/sentry/rails/tracing/active_record_subscriber.rb
  sentry-rails/spec/sentry/rails/tracing/action_controller_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/action_view_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/active_record_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing_spec.rb
  sentry-rails/spec/support/test_rails_app/app.rb
  sentry-rails/spec/support/test_rails_app/test_template.html.erb
  sentry-ruby/lib/sentry/client.rb
  sentry-ruby/lib/sentry/rack/tracing.rb
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/spec/sentry/rack/tracing_spec.rb
  sentry-ruby/spec/sentry/span_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
Labels: enhancement, tracing

#1112 Refactor sentry-rails
  sentry-rails/lib/sentry/rails/tracing.rb
  sentry-rails/spec/sentry/rails/tracing/action_controller_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/action_view_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/active_record_subscriber_spec.rb
  sentry-rails/spec/spec_helper.rb
Labels: refactoring

#1115 Add allocation comparison for sentry-ruby and sentry-rails
  .github/workflows/sentry_rails_test.yml
  .github/workflows/sentry_raven_test.yml
  .github/workflows/sentry_ruby_test.yml
Labels: profiling/benchmarking

#1113 Sampling transaction
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/lib/sentry/rails/tracing/abstract_subscriber.rb
  sentry-rails/spec/sentry/rails/tracing/action_controller_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/action_view_subscriber_spec.rb
  sentry-rails/spec/sentry/rails/tracing/active_record_subscriber_spec.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/hub.rb
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/lib/sentry/transaction.rb
  sentry-ruby/spec/sentry/configuration_spec.rb
  sentry-ruby/spec/sentry/rack/tracing_spec.rb
  sentry-ruby/spec/sentry/span_spec.rb
  sentry-ruby/spec/sentry/transaction_spec.rb
  sentry-ruby/spec/sentry_spec.rb
Labels: enhancement, tracing

#1116 Tidy up & performance improvements
  sentry-ruby/lib/sentry/breadcrumb/sentry_logger.rb
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/dsn.rb
  sentry-ruby/lib/sentry/event.rb
Labels: refactoring

#1117 Use the shared Sentry.utc_now helper for time generation
  sentry-ruby/lib/sentry-ruby.rb
  sentry-ruby/lib/sentry/breadcrumb.rb
  sentry-ruby/lib/sentry/event.rb
  sentry-ruby/lib/sentry/span.rb
  sentry-ruby/lib/sentry/transaction_event.rb
  sentry-ruby/lib/sentry/transport.rb
  sentry-ruby/lib/sentry/transport/state.rb
  sentry-ruby/spec/sentry/transport_spec.rb
Labels: refactoring

#1118 Reorganize config options
  sentry-ruby/lib/sentry/configuration.rb
  sentry-ruby/lib/sentry/event.rb
Labels: documentation, refactoring
