Repository getsentry/sentry-ruby, pull requests merged in 2023-10, with the labels that each got.

#2120 Adopt Rails 7.1's new BroadcastLogger
  CHANGELOG.md
  sentry-rails/.gitignore
  sentry-rails/lib/sentry/rails/configuration.rb
  sentry-rails/spec/sentry/rails_spec.rb
Labels: enhancement

#2125 Update setup for Rails 7.1
  sentry-delayed_job/Gemfile
  sentry-rails/Gemfile
  sentry-rails/spec/dummy/test_rails_app/configs/7-2.rb
  sentry-rails/spec/sentry/rails_spec.rb
  sentry-sidekiq/Gemfile
  sentry-sidekiq/spec/sentry/sidekiq/sentry_context_middleware_spec.rb
Labels: testing

#2142 Fix JRuby build by pinning pysch to 5.1.0
  sentry-delayed_job/Gemfile
  sentry-resque/Gemfile
  sentry-sidekiq/Gemfile
Labels: testing

#2141 Fix puma integration for versions before v5
  CHANGELOG.md
  sentry-ruby/lib/sentry/puma.rb
Labels: bug fix

#2139 Allow customization breadcrumb data of ActiveSupportLogger
  CHANGELOG.md
  sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
  sentry-rails/lib/sentry/rails/configuration.rb
  sentry-rails/lib/sentry/rails/railtie.rb
  sentry-rails/spec/sentry/rails/breadcrumbs/active_support_logger_spec.rb
  sentry-rails/spec/sentry/rails/configuration_spec.rb
Labels: enhancement

#2148 add delayed job context into the sampling context
  CHANGELOG.md
  sentry-delayed_job/lib/sentry/delayed_job/plugin.rb
  sentry-delayed_job/spec/sentry/delayed_job_spec.rb
Labels: enhancement
